### PR TITLE
Configurable query

### PR DESCRIPTION
**Pull request by dr4ke616**
Enhancement to allow configurable based queries.

**Summary of changes:**

- `datejs` dependancy needed to be added to allow for human readable time based queries.
- Code added to read and serialise query from config into url encoded parameters. 
- README updated with examples.

### CODE REVIEW

**Comment by dr4ke616** [comment]
Hey, im not sure how to resolve the travis build issue. As for the security risk, is that a bad thing seen as its used only as a mirror module?

**Comment by fewieden** [comment]
i will take care about travis, as it is not set up correctly yet.

will look into this pr(vulnerability and functionality) tomorrow

**Comment by fewieden** [comment]
ok i have linted everything and removed datejs and used momentjs instead, what do you think about discover date part?

**Comment by dr4ke616** [comment]
Looks nice, and removes the extra dependancy. 👍

**Pull request merged**
